# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "胡杨的个人博客"
headline: "木易沙鸥"
description: 
   博学笃志 格物明德<br> ———— 做个拥有求知欲的小白
   

email: "ihuyang@hotmail.com"
weibo: "@huhu_Lucky"
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/index_bgimg.jpg"
wechat_code: "/assets/images/wechat_code.JPG"

name: "Hu Yang"
author_en: "Hu Yang"
author_cn: "胡杨"
author_info: "中国&nbsp;上海市&nbsp;&nbsp;&nbsp;&nbsp;25岁"
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://ihuyang.me" # the base hostname & protocol for your site
baseurl: ""
#设置博文的url格式
permalink: /:categories/:title.html
#used to display twitter cards
twitter_handle: '@dirkfabisch'


#weibo
weibo_icon:	"/assets/images/weibo.png"
weibo_url:	"http://weibo.com/airhy"
weibo_desc: "关注微博"

#wechat
wechat_icon: "/assets/images/wechat.png"
wechat_url:	"/assets/images/wechat_code.JPG"
wechat_desc: "加我微信"

